### ISSUE TITLE
double overlapping context menus (on Mac)

### ISSUE THREAD

**Issue by luckman212** [NomarCub/obsidian-copy-url-in-preview#1]
hey @NomarCub thank you for making this !! I have wanted this for a while.  Hope they make it a native function one day. 

One thing though, not sure it's fixable... on macOS, I now get 2 menus when right clicking a link:  the system-level one and the Electron one beneath it. 

see video:

https://user-images.githubusercontent.com/1992842/125866102-fa4bb5ca-b346-4c84-8f7a-6415cf143c95.mp4

**Comment by NomarCub** [comment]
I made a new release with a possible fix.

**Comment by luckman212** [comment]
It works! 🚀
