### ISSUE TITLE
`Open PDF externally` through link hover opens note, not pdf

### ISSUE THREAD

**Issue by NomarCub** [NomarCub/obsidian-copy-url-in-preview#14]
![pdf](https://user-images.githubusercontent.com/5298006/178160090-dbb6321b-0f83-4d34-90c5-2c579e030f51.gif)

Embedded pdfs and panes for pdfs work, but menus on hover previews open the markdown file they are in, not the pdf.
@mnaoumov could you take a look at this?

**Comment by mnaoumov** [comment]
ok, checking
