### ISSUE TITLE
Null errors

### ISSUE THREAD

**Issue by NomarCub** [NomarCub/obsidian-copy-url-in-preview#16]
I got these errors on console when hovering above normal links. There was no visible malfunctioning.

![Pasted image 20220715193251](https://user-images.githubusercontent.com/5298006/179278925-8c0ced16-06d8-48e3-956a-5d25dd9f5644.png)

![Pasted image 20220715143827](https://user-images.githubusercontent.com/5298006/179278882-442abeec-42fb-4540-9e8a-3dab4476a4d1.png)

Also I recently added `strictNullChecks` to tsconfig.json and made the existing code able to compile in a crude way in this commit: https://github.com/NomarCub/obsidian-copy-url-in-preview/commit/f6f9ef4298b03c5f0c3e1562ef702ebd9e58f05b.
But the errors come with the version before strictNullChecks too.

@mnaoumov would you take a look at this? You'd probably know what can and can't be null around the PDF feature better than me.

**Comment by mnaoumov** [comment]
Ok, I am on it
