### ISSUE TITLE
Open Image Externally on right click

### ISSUE THREAD

**Issue by mwolter805** [NomarCub/obsidian-copy-url-in-preview#18]
Hello,
Would like to see if it's possible to add the ability to "Open image externally" when an attached image is right clicked. Ideally this option would be added below "Copy image to clipboard" when the image is right clicked which would reduce the steps from four to two to open the image externally.

Currently the user has to switch to editing view, click image, right click the image URL and finally selecting "Open in default app".

Thank you,
Matt

**Comment by NomarCub** [comment]
Just to make sure I get this, you'd like something like the existing "Open in default app" context menu item when right clicking, for local images I assume?
![image](https://user-images.githubusercontent.com/5298006/196515736-0f19f2eb-682e-4ae5-8473-23009b88c682.png)

**Comment by mwolter805** [comment]
Correct, this would be for local images with either a relative or absolute file path. Thank you

**Comment by NomarCub** [comment]
@mwolter805, please try this work in progress: [main.zip](https://github.com/NomarCub/obsidian-copy-url-in-preview/files/9845202/main.zip)!
The solution I found works on my machine, but uses unofficial Obsidian API, so I want to make sure. What OS are you on, by the way?

**Comment by mwolter805** [comment]
@NomarCub Works great! I'm on Mac OS 12.6. Thank you for looking into this so quickly.

**Comment by NomarCub** [comment]
You're welcome! I've made a release now.
I missed this functionality too at work, but it didn't even cross my mind that I could implement it.
