### ISSUE TITLE
FR - Add "reveal in finder" to plugin context menu

### ISSUE THREAD

**Issue by Friedolito** [NomarCub/obsidian-copy-url-in-preview#20]
First thank you for the plugin! It saved me already hours of looking trough the enormus context menu. 

A thing that I do really often, is to reveal images in the finder, because I have to edit them in a different application. For that I have to go trough the obsmd context menu.
I habitual try to use the context of the plugin and then have to select the image link to get the option. So having it on a right click there as well would be neat! 

I don't now if there is anybody out there, wishing for the same, but I would love to have it! 

Best Regards. :)

**Comment by NomarCub** [comment]
I'm glad the plugin was useful for you!
By reveal in finder do you mean the `Show in system explorer` or `Reveal in file navigation`?
![image](https://github.com/NomarCub/obsidian-copy-url-in-preview/assets/5298006/274a25e9-0436-4571-ba4c-97885e2b70ce)

**Comment by Friedolito** [comment]
I mean the "show file in system explorer" command. 
Sorry, I'm on mac and sometimes forget about other OS's names ..

**Comment by NomarCub** [comment]
Here's a modified dev version with the feature. Could you please give it a try?
Also, looking into the Obsidian code, it's probably not called system explorer on Mac. Could you please show what the original Obsidian context menu shows on Mac? I guess it's probably Show in finder, but I want to stay consistent, and it's hard to navigate the obfuscated Obsidian code.
[main.zip](https://github.com/NomarCub/obsidian-copy-url-in-preview/files/11470519/main.zip)

**Comment by Friedolito** [comment]
Thank you for looking into it!!
It does now exactly what I thought of. 

On macOS it is "reveal in finder"
<img width="167" alt="image" src="https://github.com/NomarCub/obsidian-copy-url-in-preview/assets/53973194/097c60dd-0db7-47a8-8320-2d2703ce9548">

**Comment by NomarCub** [comment]
Nice. I'm gonna make a release in a couple of days then.

**Comment by NomarCub** [comment]
It's done, you can update to [1.5.0](https://github.com/NomarCub/obsidian-copy-url-in-preview/releases/tag/1.5.0) from Obsidian.

**Comment by Friedolito** [comment]
Thank you a lot !!
