### ISSUE TITLE
Preview PDF Externally with right click instead of hover?

### ISSUE THREAD

**Issue by weldcloudnotes** [NomarCub/obsidian-copy-url-in-preview#25]
Frequently you'll have a PDF inline with your notes so that you can preview it while reading. This means that the context menu will be enabled and you can no longer scroll (both for the PDF content, and the Note you're embedding a PDF in) and you need to click somewhere to disable the context menu. Currently it hinders the workflow a little bit.

I also feel like it goes against the general philosophy of this plugin, where you can copy image to clipboard by right clicking, and copy url by right clicking, but on PDFs, you hover instead of right clicking.

This plugin is great regardless, I use it daily!

**Comment by NomarCub** [comment]
The built in Obsidian viewer is about to change, so I'll probably wait a little for new functionality. I'm not sure how overriding the right click is possible technically, and if it clashes with other built in PDF functionalities (selecting text, etc). @mnaoumov what do you think?

**Comment by mnaoumov** [comment]
@NomarCub I already made a PR to support new pdf viewer from Obsidian 1.3.0 . In previous pdf viewer it was not possible to handle right click. The new pdf viewer I didn't check if we can switch to the right click instead

**Comment by Friedolito** [comment]
I think this will fit in her: 
The context menu being triggered on hovering, will interfere interacting with pdfs inside obsmd. 
<img src="https://github.com/NomarCub/obsidian-copy-url-in-preview/assets/53973194/e84073f6-ff8c-46bb-bfc6-6ca1d05cd711" alt="drawing" width="200"/>


Right click would be neat, or an option to disable the plug-in only for pdfs, for the people who prefere working on pdfs inside obsmd. 

Thanks a lot for the plug-in! :)

**Comment by NomarCub** [comment]
I added an option to disable the PDF context menu.
The Obsidian PDF viewer has this feature covered now anyway.

**Comment by Friedolito** [comment]
Thank you for the quick action! :)

**Comment by NomarCub** [comment]
The disable option and the built in Obsidian functionality addresses the concerns here.
If @weldcloudnotes or someone else has no objection, I'll close this.

Here's the native PDF menu now: 
![image](https://github.com/NomarCub/obsidian-copy-url-in-preview/assets/5298006/48b20e38-5627-4669-bb6a-e096bc1998ee)

**Comment by m-beau** [comment]
I spent half a year losing my mind over this hover beahviour without being able to identify its origin! Thank you for implementing an option to disable the PDF context menu (I would even suggest disabling it by default!).

**Comment by NomarCub** [comment]
Yeah, I should have done that earlier. I changed the default to disabled now. I'll make a release soon.
