### ISSUE TITLE
Reveal file in navigation support File Tree Alternative Plugin

### ISSUE THREAD

**Issue by xtmu** [NomarCub/obsidian-copy-url-in-preview#29]
I use [File Tree Alternative Plugin](https://github.com/ozntel/file-tree-alternative) as OB's default file explorer, please provide setting for which file-explorer to reveal in when using _reveal file in navigation_.

**Comment by ozntel** [comment]
Not sure if I understood correctly but if you want to dispatch a reveal active file event from the Context menu you have from the plugin:

```ts
let fileToReveal = app.vault.getAbstractFileByPath(ANYFILEPATH); // or you don't need it if you already have TFile or TAbstractFile variable
let revealFileEvent = new CustomEvent({
    'fta-reveal-file',
    detail: {
        file: fileToReveal,
    },
});
window.dispatchEvent(revealFileEvent);
```

**Comment by xtmu** [comment]
I want the context menu *reveal file in navigation* to reveal file in File Tree Alternative file explorer.
Please give me a hint about where to place that [API](https://github.com/ozntel/file-tree-alternative/issues/174#issuecomment-1751985076), and how to use it.

**Comment by NomarCub** [comment]
Hi!
I did a demo on this branch: https://github.com/NomarCub/obsidian-copy-url-in-preview/compare/main...reveal-in-file-tree
Could you please try it, to see if it's good for you?
Here's the test version zipped: [copy-url-in-preview-file-tree-test.zip](https://github.com/user-attachments/files/15936085/copy-url-in-preview-file-tree-test.zip).

If this works fine, I'll add an option to disable the native reveal option, if you still want that.
~~One issue I found is this command doesn't focus the tree view if it's not in focus already, unlike the native one. I'd have to ask its maintainer for that if that's something you also need.~~

**Comment by ozntel** [comment]
Hi @NomarCub, I just added a functionality to focus the tree view if you trigger the custom event

**Comment by NomarCub** [comment]
Thank you!

**Comment by NomarCub** [comment]
@xtmu please take a look at this, I don't want to add a new feature that no one would use.

**Comment by NomarCub** [comment]
@xtmu if there's no response here this month, I'll close this issue. Comment now, or in the future if you still want this.

**Comment by xtmu** [comment]
Hi, @NomarCub , sorry for late response, I didn't use computer lately because my new home has no network connection. I just tested the zip file, it's exactly what I need, thank you for your nice work. And it is good to add an option 'disable the native reveal option' for hiding *reveal file in navigation*, default status could be 'on'.

**Comment by NomarCub** [comment]
Hey @xtmu!
Could you take a look at the final version before release? It has the setting added.
[copy-url-in-preview-file-tree-test-2.zip](https://github.com/user-attachments/files/16261155/copy-url-in-preview-file-tree-test-2.zip)

**Comment by xtmu** [comment]
@NomarCub  It looks friendly enough to both 'Files' user and 'File Tree Alternative' user. Thanks so much! Looking forward to updating a release.

**Comment by NomarCub** [comment]
Thank you for your patience and your cooperation!
The release is out, here: https://github.com/NomarCub/obsidian-copy-url-in-preview/releases/tag/1.9.0
