### ISSUE TITLE
Error, could not copy the image!

### ISSUE THREAD

**Issue by JoeYoLee** [NomarCub/obsidian-copy-url-in-preview#30]
Error, could not copy the image!
The above error occurs when I right-click to copy the picture in Obsidian. It should be noted that my picture is a link.
How to solve it? Thank you very much.

<img width="283" alt="image" src="https://github.com/NomarCub/obsidian-copy-url-in-preview/assets/60375366/f1df1fbd-2891-4c15-83c3-a2134ee432e8">

**Comment by NomarCub** [comment]
Hi!
Please share the link too, so I can reproduce the issue.

**Comment by NomarCub** [comment]
I'll close this issue for now, but I'll respond if you have more questions and reopen if you provide more info.
