### ISSUE TITLE
"Image was temporarily saved and will be removed in one minute"

### ISSUE THREAD

**Issue by btbristow** [NomarCub/obsidian-copy-url-in-preview#31]
Hi, I just installed this plugin. It seems to work in edit OR reading mode and is very useful on mobile!

But, I was wondering what that message is. It pops up in iOS when I long press any image.

**Comment by NomarCub** [comment]
I tested on Android before I released for mobile, but I mostly use it on desktop, and don't have an iPhone.
Could you provide more details? What is the issue? Could you take a screenshot or video?

**Comment by NomarCub** [comment]
I might get what you mean now. That notification describes how the plugin does copying on mobile for online images. Android doesn't have a clipboard the same way a desktop OS does, so if the image is not a local file we download it temporarily so it can be shared.
See more at the GitHub issue that sparked this: https://github.com/NomarCub/obsidian-copy-url-in-preview/issues/5.

I'll close this issue for now, but I'll respond if you have more questions and reopen if there's an issue.
