### ISSUE TITLE
obsidian1.5.3，”Open image in default app“ is disappeared

### ISSUE THREAD

**Issue by calmwaves111** [NomarCub/obsidian-copy-url-in-preview#32]
for images
- Copy Image
- Open image in default app
- Show in system explorer
- Reveal file in navigation

however，when I update to obsidian 1.5.3，there is only “copy image to clipboard”

![image](https://github.com/NomarCub/obsidian-copy-url-in-preview/assets/56907077/b2b0d266-2187-40ba-b3a4-5d353a56b74d)

**Comment by NomarCub** [comment]
Thanks for the issue!
I just fixed this in 1.5.2. Let me know if it doesn't work.
