### ISSUE TITLE
Open image in new tab functionality

### ISSUE THREAD

**Issue by NomarCub** [NomarCub/obsidian-copy-url-in-preview#36]
Copy the behaviour of middle clicking / using "Open link in new tab" / "Open link" when right clicking the image's embed text in edit mode.
This may suit some people's workflows more, as it stays within Obsidian rather than opening the image in the default app.

In addition to new context menu item(s), it would be nice to be able to optionally middle click on the image directly to open in a new tab.

*Implementation*: maybe [getLeaf](https://github.com/obsidianmd/obsidian-api/blob/8b2eda0f24285636c8aa116972643e5233a23dc1/obsidian.d.ts#L4516) could get us there.

**Comment by NomarCub** [comment]
Come to think of it, this might be a duplicate of https://github.com/NomarCub/obsidian-copy-url-in-preview/issues/26

**Comment by waterproofsodium** [comment]
Pull request https://github.com/NomarCub/obsidian-copy-url-in-preview/pull/37
There's also the option to disable the middle mouse button, in case users don't want a "context menu plugin" to use middle mouse.
May require testing on mobile devices, if support wanted.

**Comment by waterproofsodium** [comment]
Fixed a bug of displaying the whole image path. Now it just shows the name. Please when pulling ensure it contains all ~~3~~ 4 commits (I do not know if that is the default)

**Comment by waterproofsodium** [comment]
reminder that the pull request is still pending. it doesn't hurry

**Comment by NomarCub** [comment]
Hey @waterproofsodium! Would you take a look at the things I wrote in comments to the pull request?

**Comment by waterproofsodium** [comment]
Thanks haven't seen that. Will work on it now.

**Comment by NomarCub** [comment]
Thanks for your contribution!
I just released [1.7.0](https://github.com/NomarCub/obsidian-copy-url-in-preview/releases/tag/1.7.0), which includes the new feature. Let me know if there's anything wrong, either here or in a new issue.
