### ISSUE TITLE
Use native Obsidian file opening for `Open in new tab`

### ISSUE THREAD

**Issue by Iwuaa** [NomarCub/obsidian-copy-url-in-preview#39]
Opening image in new tab creates tab named "New Tab" instead of naming the tab after the image.
The tab is also a web browser like tab with url field.
![image](https://github.com/NomarCub/obsidian-copy-url-in-preview/assets/18384005/7e9cb0da-9b42-40fd-af69-c15b4f45f6e5)

Intuitive behavior would be opening image the same way as from file navigation - image path is shown, file is highlighted in navigation 
![image](https://github.com/NomarCub/obsidian-copy-url-in-preview/assets/18384005/7317070b-6a28-4260-96bb-66edad55789e)

**Comment by NomarCub** [comment]
I just made a release fixing this, let me know if there's still something wrong.
