### ISSUE TITLE
Why url-copy functionality is removed?

### ISSUE THREAD

**Issue by GYukai** [NomarCub/obsidian-copy-url-in-preview#41]
I'm searching for a plugin to implement that and found this plugin. But why is this removed?

**Comment by NomarCub** [comment]
You can see it in the readme. I removed it, because Obsidian made it themselves in 1.5.

> This plugin used to be called "Copy Image and URL context menu". It had link URL copying functionality (see [1.5.2](https://github.com/NomarCub/obsidian-copy-url-in-preview/tree/1.5.2) and prior), but that was removed when it was included in Obsidian 1.5.

You can install an old version of this plugin manually, but you won't find functionality that's not already in Obsidian.

**Comment by GYukai** [comment]
I see, I misunderstood the functionality. What I was searching for is copying the image **from** the url. Is there any plan for that?

**Comment by NomarCub** [comment]
Do you mean right clicking on an image embedded from an URL?
That's already part of the plugin, but it broke some time ago, here's the issue tracking it: https://github.com/NomarCub/obsidian-copy-url-in-preview/issues/35
Or do you mean right clicking on an URL text in a note to copy the image to the clipboard?

**Comment by GYukai** [comment]
> Do you mean right clicking on an image embedded from an URL?
> That's already part of the plugin, but it broke some time ago, here's the issue tracking it: https://github.com/NomarCub/obsidian-copy-url-in-preview/issues/35

Exactly this, I reproduced the behavior. Sorry to know it's broken.
