### ISSUE TITLE
The longtap does not work in version 1.9.0

### ISSUE THREAD

**Issue by Amo906** [NomarCub/obsidian-copy-url-in-preview#45]
I recently downloaded this latest plugin on my Android phone, but I found that Longtap does not work and nothing happens
When I try 1.6.0 and 1.8.0 it is working

**Comment by NomarCub** [comment]
Thank you for the version info, made it really easy to find the bug!
Would you test the fix before release please?
[main.zip](https://github.com/user-attachments/files/16917127/main.zip)

**Comment by Amo906** [comment]
> Thank you for the version info, made it really easy to find the bug! Would you test the fix before release please? [main.zip](https://github.com/user-attachments/files/16917127/main.zip)

I tested this file and it works fine on both my computer and phone. 
Thanks for your work.

**Comment by NomarCub** [comment]
This fix was released in this version: [1.9.1](https://github.com/NomarCub/obsidian-copy-url-in-preview/releases/tag/1.9.1)
