### ISSUE TITLE
Feature request: Copy note with images

### ISSUE THREAD

**Issue by CharlesLennon** [NomarCub/obsidian-copy-url-in-preview#47]
Hi, i would love to be able to CTRL-A right click copy (or hot key) a note and have the images included or right-click a note and copy with images

The goal is to have text above and below the image without having to copy the image on its own every time i need to use it

**Comment by NomarCub** [comment]
I won't implement this, sorry. I spoke about it here: https://forum.obsidian.md/t/copy-image-from-a-note/2318/24.
You can look around the forum or GitHub for someone else who'd develop it.

**Comment by CharlesLennon** [comment]
> I won't implement this, sorry. I spoke about it here: https://forum.obsidian.md/t/copy-image-from-a-note/2318/24. You can look around the forum or GitHub for someone else who'd develop it.

Any objections to having it as a feature? (Developed by someone else and PR'ed in)

**Comment by NomarCub** [comment]
No, I'd merge it if someone properly implemented it.
But I'm skeptical about its complexity, and it doesn't fit well with the other features.
