### ISSUE TITLE
Feature Request - Ability to open embedded PDFs in the default app

### ISSUE THREAD

**Issue by mnaoumov** [NomarCub/obsidian-copy-url-in-preview#9]
It will help to share them especially on the mobile app. Similar to the sharing images one

**Comment by mzwoelfer** [comment]
Doesn't work for me with Default App Firefox Browser.

I am running Linux Ubuntu LTS 20.
My default App to open PDFs is the Firefox browser.
When clicking the "Open PDF externally" nothing happens.
- Restarted
- Deinstalled / isntalled Obsidian
- Deinstalled / Installed the Plugin

Is this intended?

**Comment by NomarCub** [comment]
Are there any console messages or errors while this happens?

@mnaoumov what do you suspect?

**Comment by mnaoumov** [comment]
I would use something like https://github.com/Sysinternals/ProcMon-for-Linux to see if the Obsidian tried to start the process to open the PDF
